### ISSUE TITLE
Add legacy blast

### ISSUE THREAD

**Issue by colinbrislawn** [biocore/conda-recipes#10]
The repo tagline reads

> bioinformatic tools like blast+...

What version of blast would be useful?
- BLAST+: ftp://ftp.ncbi.nlm.nih.gov/blast/executables/blast+/LATEST/
- legacy BLAST: ftp://ftp.ncbi.nlm.nih.gov/blast/executables/release/LATEST/

**Comment by colinbrislawn** [comment]
The [qiime docs](http://qiime.org/install/install.html#installing-qiime-natively-with-a-full-install) recommend legacy blast blast-2.2.22 from the official [NCBI site](ftp.ncbi.nlm.nih.gov/blast/executables/release/2.2.22/). Some qiime scripts can make use of `blastall` and other functions, and I'm not sure if these are different in 2.2.26, which is the [latest version](ftp.ncbi.nlm.nih.gov/blast/executables/release/LATEST) at the time of writing. 

I'll see if I can get 2.2.22 working, unless there is want for `BLAST+` or 2.2.26.

Also blast is [Public Domain](http://www.ncbi.nlm.nih.gov/IEB/ToolBox/CPP_DOC/lxr/source/scripts/projects/blast/LICENSE)
Also blast has [publicly available source code](http://www.ncbi.nlm.nih.gov/viewvc/v1/trunk/c%2B%2B/src/app/blast/?sortby=date#dirlist)

**Comment by rob-knight** [comment]
It would probably be worth updating the wrappers to use a current version of blast but no-one has had time to benchmark it and we know the old version works…

**Comment by colinbrislawn** [comment]
I'll take this one.

**Comment by colinbrislawn** [comment]
I can't find source for 2.2.22, only these precompiled binaries. 
ftp://ftp.ncbi.nlm.nih.gov/blast/executables/release/2.2.22/blast-2.2.22-x64-linux.tar.gz 
ftp://ftp.ncbi.nlm.nih.gov/blast/executables/release/2.2.22/blast-2.2.22-universal-macosx.tar.gz 
ftp://ftp.ncbi.nlm.nih.gov/blast/executables/release/2.2.22/blast-2.2.22-x64-win64.exe 

What if I make `build.sh` download the right binary for the `$TRAVIS_OS_NAME` instead of actually building it? This should work, but it's not a true 'build'. 

Any better ideas?

**Comment by colinbrislawn** [comment]
I'll approach this like #34. This should be easy after I get blast+ working...
