### ISSUE TITLE
Add Diamond

### ISSUE THREAD

**Issue by RNAer** [biocore/conda-recipes#16]

**Comment by colinbrislawn** [comment]
I'll take this one.
https://github.com/bbuchfink/diamond/

**Comment by RNAer** [comment]
go ahead. Notice its license. I already got permission from Benjamin to
build and distribute diamond thru anaconda biocore. You're good to go.

**Comment by RNAer** [comment]
what's the status on this?

**Comment by colinbrislawn** [comment]
I have clarified that Diamond is under the BSD license. I will be adding it later this week.

Unless you want to add it. That's fine with me too.

Keep me posted!

**Comment by RNAer** [comment]
cool. if you can take a stab at it later this week, I'll let you do it. :-)

**Comment by Jorge-C** [comment]
It might make sense to ask them to add the license to the repo?

**Comment by Jorge-C** [comment]
Oh, they actually have it, but it's inside /src instead of in the main folder. Sorry for the noise!

**Comment by colinbrislawn** [comment]
That's a valid concern, @Jorge-C (He also has some parts of the GPL floating around. After bbuchfink/diamond#19 is resolved, this repo should be fully BSD.)

**Comment by colinbrislawn** [comment]
@RNAer You can take this one and I'll focus on Blast+ and legacy blast.

(I took a shot at it but the current way for diamond to be built from source is not working well on my mac.
https://github.com/bbuchfink/diamond#compiling-from-source)

**Comment by RNAer** [comment]
it is not worth the time to debug the compilation on linux box. I'll just use the avail exe for now. what do you guys think?

**Comment by colinbrislawn** [comment]
I think using the binary is OK. Because we have source I would prefer
building from source, but anything works.

**Comment by Jorge-C** [comment]
What about binary for now but open an issue in their repo with the error messages, so that we're able to build from source at some point?

For the record, cloning the repo, mkdir build, cd build, cmake .. -DCMAKE_INSTALL_PREFIX=$PREFIX works on my linux box out of the box.

**Comment by RNAer** [comment]
last try. do you have any clue why `boost` is still not found after `conda
install boost`?

**Comment by Jorge-C** [comment]
No idea, sorry. I found a conda recipe for boost [here](https://github.com/menpo/conda-boost) (they also build it and upload it through travis), and just asked them what are the differences.

**Comment by mortonjt** [comment]
Just as a heads up, boost-1.57 is installed in this conda recipe.  diamond actually requires boost-1.59

**Comment by jdereus** [comment]
believe this recipe builds on travis because of the inclusion of the menpo channel.  seems without modifying the .condarc file, that is not possible in this build recipe.  recommend cloning the boost and glibc recipes to local scope recipes here to resolve dependencies.  boost is installed (v1.57 as noted) but nothing more recent is available out of the box.

**Comment by colinbrislawn** [comment]
This travis build claims to incorporate boost 1.59
https://travis-ci.org/ignacio/LuaNode/jobs/75520961

Another one using boost 1.59
https://travis-ci.org/ComputationalRadiationPhysics/alpaka/jobs/84681506

**Comment by mortonjt** [comment]
I'm not so sure about that.

Whenever I try to conda install diamond, it'll only download boost 1.57.

And this seems to be a prevalent problem across multiple conda recipes repos.  Looks like repos like [this one](https://github.com/faircloth-lab/conda-recipes/tree/master/recipes) just create their own boost recipe.

**Comment by RNAer** [comment]
@mortonjt and @jdereus , even with boost 1.59:

```
$ conda list | \grep "\(diamond\)\|\(boost\)"
boost                     1.59.0                   py27_0  
diamond                   0.7.9.dev0                    0  
```

 I still have problem running it:

```
$ diamond
dyld: lazy symbol binding failed: Symbol not found: __ZNSt8__detail15_List_node_base7_M_hookEPS0_
  Referenced from: /Users/zech/anaconda/envs/dev/bin/diamond
  Expected in: /usr/lib/libstdc++.6.dylib

dyld: Symbol not found: __ZNSt8__detail15_List_node_base7_M_hookEPS0_
  Referenced from: /Users/zech/anaconda/envs/dev/bin/diamond
  Expected in: /usr/lib/libstdc++.6.dylib

Trace/BPT trap: 5
```
