### ISSUE TITLE
Add blast+

### ISSUE THREAD

**Issue by RNAer** [biocore/conda-recipes#19]

**Comment by colinbrislawn** [comment]
I'll take this one.

**Comment by RNAer** [comment]
:+1: Thanks!

**Comment by colinbrislawn** [comment]
Source for latest blast+ is available here, so we can build from source.
ftp://ftp.ncbi.nlm.nih.gov/blast/executables/LATEST/ncbi-blast-2.2.31+-src.tar.gz 

We can also download precompiled binaries, like for #10 
ftp://ftp.ncbi.nlm.nih.gov/blast/executables/LATEST/ncbi-blast-2.2.31+-x64-linux.tar.gz 
ftp://ftp.ncbi.nlm.nih.gov/blast/executables/LATEST/ncbi-blast-2.2.31+-universal-macosx.tar.gz 
ftp://ftp.ncbi.nlm.nih.gov/blast/executables/LATEST/ncbi-blast-2.2.31+-win64.exe 

Thoughts?

**Comment by RNAer** [comment]
I would say binaries.

**Comment by colinbrislawn** [comment]
Can do!

I'm not sure how this will work for Windows as Travis does not support Windows as a build environment. I may wait for windows deployment until #13 is implemented, then add it.

**Comment by colinbrislawn** [comment]
Finally addressed in #42. You can close this.
