### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by Jorge-C** [biocore/conda-recipes#2]
It'd be nice to have travis building every package as CI, and if successful uploading binaries to binstar.

**Comment by ElDeveloper** [comment]
:+1:

**Comment by Jorge-C** [comment]
Haha, turns out there's a demo project for doing exactly this : https://github.com/mbalasso/python-appveyor-travis-conda-example (builds binaries for windows and linux). Travis can test in OSX too, so it should be possible to extend it further.

**Comment by Jorge-C** [comment]
Windows support tracked in #13.
