### ISSUE TITLE
Add muscle

### ISSUE THREAD

**Issue by colinbrislawn** [biocore/conda-recipes#25]
Need to check muscle license...
Should ask Robert Edgar for permission too.

**Comment by colinbrislawn** [comment]
Muscle has been released into the public domain: http://www.drive5.com/muscle/manual/license.html

**Comment by colinbrislawn** [comment]
The last major release of muscle was 3.8.31. Newer versions include 3.8.425 (bug fix for long sequences) and 3.8.1551 (latest source, builds on newer o/s's).
http://www.drive5.com/muscle/downloads.htm 

What version would you use the most?
(Is anyone interested in this? Perhaps muscle has been fully supplanted by MAFFT and pynast...)

**Comment by colinbrislawn** [comment]
Yeah... I don't think this is needed. I think people are more likely to use MAFFT as a general aligner or Infernal + SSU-ALIGN for rRNA amplicons. Given that we already include MAFFT and Infernal, I'll close this for now. 

If anyone is interested in deploying Muscle, let me know!

**Comment by wasade** [comment]
Wouldn't this be redundant with bioconda's [recipe](https://bioconda.github.io/recipes/muscle/README.html) too?

**Comment by colinbrislawn** [comment]
Sooo redundant. Let's not add muscle.
