### ISSUE TITLE
Add biom-format

### ISSUE THREAD

**Issue by colinbrislawn** [biocore/conda-recipes#36]
https://github.com/biocore/biom-format

I know this would be covered in #3, but biom-format is a stand-alone project, it is being updated as part of QIIME 2, and I would find it immediately useful.

**Comment by wasade** [comment]
:+1:, ideally this ensures h5py comes with it

**Comment by colinbrislawn** [comment]
Exactly! And `biom from-uc`.

```
conda config --add channels http://conda.anaconda.org/biocore
conda install vsearch biom
```

:flushed:

**Comment by gregcaporaso** [comment]
I have a couple of updates ([#645](https://github.com/biocore/biom-format/issues/645) and [#679](https://github.com/biocore/biom-format/issues/679)) going into biom this week which I think would be generally useful. If you could hold off for a few days on this one, I could probably get a 2.1.6 up that has these new pieces.

**Comment by colinbrislawn** [comment]
I've been working on this one, but some more experienced should take it.
(I've been recreating the [.travis.yml of biom-format](https://github.com/biocore/biom-format/blob/master/.travis.yml) as a conda-recipe. Very slow going...)

**Comment by Jorge-C** [comment]
Hi Colin, just a couple of tips that might help you. Sorry if you're already familiar with them!
- biom-format is pip installable, so you can use [`conda skeleton`](http://conda.pydata.org/docs/commands/build/conda-skeleton.html) to create an initial recipe.
- It might be missing h5py/numpy as dependencies, so you might have to play with that

Let us know if you're stuck in a specific problem!

**Comment by colinbrislawn** [comment]
Oh, I did not know this was on pip. Duh.
Thank you! I'll take another shot.

Colin

**Comment by colinbrislawn** [comment]
Thanks to @bgruening, biom-format is now on bioconda. We will troubleshoot any `h5py` issues there.
https://github.com/bioconda/bioconda-recipes/tree/master/recipes/biom-format

**Comment by wasade** [comment]
That is fantastic, thank you @bgruening!
