### ISSUE TITLE
blast+ isn't a valid package name

### ISSUE THREAD

**Issue by Jorge-C** [biocore/conda-recipes#38]
It seems only ascii and - are allowed? What name should we use instead?

**Comment by Jorge-C** [comment]
I created an [issue](https://github.com/conda/conda/issues/1804) at the conda tracker, because the package builds correctly and only fails to upload.

**Comment by colinbrislawn** [comment]
How about `blastplus`?

**Comment by colinbrislawn** [comment]
What if we call these `blast-plus` and `blast-legacy`? This way we can immediately sidestep the conda naming issue. These consistent names also avoid ambiguity between 'blast and blast+' or 'blast and legacy blast'.

**Comment by gregcaporaso** [comment]
+1

**Comment by Jorge-C** [comment]
:+1:

**Comment by colinbrislawn** [comment]
Addressed in #37 and #42. You can close this.

**Comment by Jorge-C** [comment]
Thanks! Cool tip: If a commit message states eg ["closes #XY"](https://help.github.com/articles/closing-issues-via-commit-messages/), that issue is automagically closed when merged into master.
