### ISSUE TITLE
add FastTree

### ISSUE THREAD

**Issue by colinbrislawn** [biocore/conda-recipes#47]
It's the default for tree-building, so I would like it.
It's under the GPLv2, as shown on the top of the source code: 
http://www.microbesonline.org/fasttree/FastTree.c 

Links here: http://www.microbesonline.org/fasttree/#Install

**Comment by wasade** [comment]
Just a note, make sure to compile with double precision

**Comment by colinbrislawn** [comment]
What variations of this program should I build? Guidance appreciated. @wasade @gregcaporaso
biocore/qiime#466

I'm thinking all with double precision, all with `sse`, and with and without MP.
`gcc -DUSE_DOUBLE -O3 -finline-functions -funroll-loops -Wall -o FastTree FastTree.c -lm`

What about these additional options in mentioned in biocore/qiime#466?
`-nt -gamma -fastest -no2nd -spr 4`

**Comment by wasade** [comment]
Recommend just doing DP with MP, I don't know what the benefit would be of
variations? Not doing openmp may be nice in the case of the library not
being installed but its pretty common to have. The other options described
are at runtime.
