### ISSUE TITLE
add burrito

### ISSUE THREAD

**Issue by colinbrislawn** [biocore/conda-recipes#57]
https://github.com/biocore/burrito
:smile: :burrito:

Also needed for #56

**Comment by colinbrislawn** [comment]
Thanks to @bgruening, burrito and burrito-fillings are now on bioconda. 
https://github.com/bioconda/bioconda-recipes/tree/master/recipes/burrito/0.9.1 
https://github.com/bioconda/bioconda-recipes/tree/master/recipes/burrito-fillings/0.1.1

**Comment by mortonjt** [comment]
Thanks for putting this together!
