### ISSUE TITLE
PR-specific travis CI

### ISSUE THREAD

**Issue by RNAer** [biocore/conda-recipes#6]
Ideally, we should only run the test the recipes that are changed in a pull request. building can take a long time, especially when large number of recipes are accumulated in the future.

**Comment by Jorge-C** [comment]
:+1:

**Comment by RNAer** [comment]
@Jorge-C , do you know any example of getting files that are changed in a pull request in github API? I think that is needed to implement this.

**Comment by Jorge-C** [comment]
It should be possible using plain git, see http://stackoverflow.com/a/25071749/1191119

**Comment by RNAer** [comment]
I think you need github API to get which branch the PR is from, but I am
stepping into things I am not familiar with here.

**Comment by colinbrislawn** [comment]
What if we did this inside of `ci/main.py`?

You wrote some great code that gets the version number of each recipe in the repo and each package available on binstar. 
https://github.com/biocore/conda-recipes/blob/master/ci/main.py#L21
https://github.com/biocore/conda-recipes/blob/master/ci/main.py#L33-L35

Currently, `build_upload()` builds everything, checks if it's on binstar, then tries to upload. What if `built_upload()` checked binstar _first_, then only proceed to build packages with a different version number?

**Comment by RNAer** [comment]
That's certainly an option. what if something changes on the recipe of a
package of the same version? I'd like to rebuild that too. Is this a use
case or I am just too paranoid?

**Comment by colinbrislawn** [comment]
You are right, that's a good use case. Its also possible that someone builds and uploads an unworking package with the same version, which we would want to rebuild using Travis-CI.

What if we captured changes in your current repo like [this](http://stackoverflow.com/questions/5162800/git-diff-between-cloned-and-original-remote-repository):

``` bash
git remote add publicversion https://github.com/biocore/conda-recipes
git fetch publicversion 
git diff --name-only publicversion/master
```

That code should work regardless of what you have done with your repo or branches. We then run `build_upload_recipes()` only on directories in that list.

**Comment by RNAer** [comment]
It will work locally, but is this doable on Travis?

**Comment by Jorge-C** [comment]
A rebuild could be forced by increasing the [build number](http://conda.pydata.org/docs/building/meta-yaml.html#build-number-and-string)
in the conda recipe

2015-10-26 12:33 GMT-06:00 Zech Xu notifications@github.com:

**Comment by colinbrislawn** [comment]
I think this would work on travis. You can pipe the result of `git diff` into a text file and have `main.py` read each line.

I like @Jorge-C's suggestion. It seems less improvised then mine. Have you done something like this before? I'm pretty new to Travis and continuous integration in general.

**Comment by RNAer** [comment]
awesome, I like the solution of build number. that will solve all the
problem - the build number can be fetched from the remote and compare to
the one in the recipe:

{
  "prodigal": [
    {
      "arch": "x86_64",
      "binstar": {
        "channel": "main",
        "owner_id": "5621521bab59360b0dd04062",
        "package_id": "5623417dab59360b0ed043d8"
      },
      *"build": "0", *
      "build_number": 0,
      "channel": "biocore",
      "depends": [
        "libgcc"
      ],
      "extracted": true,
      "features": [],
      "fn": "prodigal-2.6.2-0.tar.bz2",
      "full_channel": "https://conda.anaconda.org/biocore/osx-64/",
      "installed": false,
      "license": "GPL",
      "machine": "x86_64",
      "md5": "616d8bd5b0caef4af29206d85b21cf65",
      "name": "prodigal",
      "operatingsystem": "darwin",
      "platform": "osx",
      "requires": [],
      "size": 931989,
      "subdir": "osx-64",
      "target-triplet": "x86_64-any-darwin",
      "type": null,
      "version": "2.6.2"
    }
  ]
}
